languageCode: en-us
baseURL: "https://www.prashantkatiyar.com/"
title: Prashant Katiyar
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-76R6T7WKG3

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Prashant Katiyar
  description: "Welcome to the digital space of Prashant Katiyar, a passionate tech entrepreneur, product manager, and developer relations expert based in Hyderabad, India. With a track record of catalyzing successful SaaS products within Developer Tools, Hiring, Web-3, and Retail Tech Startups, I've driven ventures that accumulated over $3.5 million in revenue. As the Co-Founder & Chief Product Officer of CometLabs since May 2021, I've spearheaded the development of a cutting-edge cloud-based IDE, leveraging GenAI for comprehensive code analysis and project evaluations. Our innovative approach secured INR 1.1 Cr preseed funding and fostered a vibrant community of 120K developers and 18,000 active users. Under my leadership, a dedicated team of 11 engineers brought this vision to life, setting benchmarks in performance and efficiency. Prior to CometLabs, my tenure as an Associate Product Manager at Hapramp Studios and a Product Manager Intern & FullStack Developer at Moptra Infotech honed my skills in enhancing product experiences, conducting A/B testing, and driving revenue growth by exploring new models like NFT Minting within the Web3 market. Equipped with a B.Tech in ECE from Indian Institute of Information Technology (IIIT), Guwahati, and enriched by entrepreneurial studies at Stanford University Graduate School of Business, I bring a robust foundation to product strategy, business analysis, user research, and community building. I've been recognized as a Top 30 Finalist at HYSEA 10X Product Awards & Expo in 2023 and a Top 5 Finalist at EO Global Student Entrepreneur Awards (GSEA) in 2023, underscoring my commitment to innovation and excellence. Explore my portfolio at prashantkatiyar.com and connect with me on LinkedIn or GitHub (@prashantkatiyar9777) to delve deeper into my journey, projects, and insights into the tech realm."
  
  keywords: [Blog, Portfolio, Product Manager, Startup Founder, CTO, Developer, Cloud-based IDE, GenAI, Agile Workflows, UI/UX Design, GitHub, Vercel, Jira, Trello, JavaScript, Python, ReactJS, AWS, Product Strategy, User Research, Community Building, PRD, A/B Testing, KPIs, IIIT, Stanford University, HYSEA 10X Product Awards, EO Global Student Entrepreneur Awards, CometLabs, Hapramp Studios, Moptra Infotech, Dunzo App, FamPay App, NFT Minting, Web3 Market]

  author: Prashant Katiyar
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "prashant.png"
    favicon16x16: "prashant.png"
    favicon32x32: "prashant.png"
    apple_touch_icon: "prashant.png"
    safari_pinned_tab: "prashant.png"
    disableFingerprinting: true

  label:
    text: "k.prashant__"
    icon: "images/prashant c.png"
    iconHeight: 28

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Prashant Katiyar"
    subtitle: "Tech Founder & Product Manager"
    imageUrl: "images/prashant.png"
    imageWidth: 180
    imageHeight: 180
    imageTitle: "Tech Founder - PM"
    buttons:
      - name: Resume
        url: "Prashant Katiyar.pdf"
      - name: About
        url: about
      - name: Projects
        url: projects
      - name: Blogs
        url: blogs
      - name: Talks & Events
        url: talks-and-events


  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/prashant-milan-katiyar/"
    - name: twitter
      url: "https://twitter.com/kprashant__"
    - name: "email"
      url: "prashant@cometlabs.in"
    - name: medium
      url: "https://medium.com/@kprashant"
    - name: github
      url: "https://github.com/prashantkatiyar9777"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 3
    - identifier: talks
      name: Talks & Events
      url: /talks-and-events
      weight: 4
    # - identifier: posts
    #   name: Posts
    #   url: /posts
    #   weight: 5

markup:
  goldmark:
    renderer:
      unsafe: true